### ISSUE TITLE
Add Python resource Think Python

### ISSUE THREAD

**Issue by amin2783** [r4victor/brtlx#2]
**Topic** 
Python

**Resource title** 
Think Python

**Resource link** 
https://greenteapress.com/wp/think-python-2e/

**Available for free** 
Yes

**Resource type** 
Book

**Is series** 
No (but similar "Think X" books are available.)

**Authors** 
Allen B. Downey

**Last update** 

**Description** 
A great book for absolute beginners in programming. Not only teaches python, but also a lot about programming in general (conventions, traditions, best practices, and general programming ideas, and most importantly, teaches **how to think like a computer scientist**). And teaches things "bottom-up", presents a problem, proposes the most intuitive solution, discusses the pitfalls, and proposes a better solution that seems easy, but guess what, that's probably one of the most famous algorithms, that you'll need to use forever. Also emphasizes on understanding what goes on under the hood, so the reader understands why he is doing what he is doing.

**Comment by r4victor** [comment]
@amin2783, thanks a lot for the contribution. This is indeed an excellent introductory book, which was missing from the website. I've changed the description for consistency with other resources and added it. We should probably add more books by Allen B. Downey.
